version: '3.8'
services:
  your-chat-api:
    build: .
    container_name: your-chat-api
    expose:
      - 8080
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}
      - URL=${URL}
      - USERNAME=root

    networks:
      - dokploy-network

    restart: always

networks:
  dokploy-network:
    external: true