version: '3.8'
services:
  your-chat-api:
    build: .
    container_name: your-chat-api
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}
      - URL=${URL}
      - USERNAME=root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.your-chat-api.rule=Host(`yourchatapi-bkvwfv-b0772f-145-79-7-209.traefik.me`)"
      - "traefik.http.routers.your-chat-api.rule=Host(`api.apiapp.shop`)"
      - "traefik.http.services.your-chat-api.loadbalancer.server.port=8080"
    restart: always