version: '3.8'
services:
  your-chat-api:
    build: .
    container_name: your-chat-api
    expose:
      - 8080
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - FRONTEND_URL=${FRONTEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}
      - URL=${URL}
      - USERNAME=root

    networks:
      - dokploy-network

    labels:
      - traefik.enable=true
      - traefik.http.routers.your-chat-api.rule=Host(`api.apiapp.shop`)
      - traefik.http.routers.your-chat-api.entrypoints=websecure
      - traefik.http.routers.your-chat-api.tls.certResolver=letsencrypt
      - traefik.http.services.your-chat-api.loadbalancer.server.port=8080
    restart: always

networks:
  dokploy-network:
    external: true